### ISSUE TITLE
Will there be 1.16.5 Version for This Mod?

### ISSUE THREAD

**Issue by diedyesterdaywashere** [KevinDaGame/FabricSearchbar#1]
Idea of this mod is cool, but it is only available on 1.18 and 1.19, so it would be nice if you could port it to 1.16.5

**Comment by KevinDaGame** [comment]
I will see if I can make it easily, maintaining 1.16.5 will not be a priority though!

**Comment by diedyesterdaywashere** [comment]
> I will see if I can make it easily, maintaining 1.16.5 will not be a priority though!

ty for your answer!

**Comment by KevinDaGame** [comment]
This should be a fully working version! I have submitted it on curseforge, but might take a while for it to be approved so here's the file
[1.16.zip](https://github.com/KevinDaGame/FabricSearchbar/files/9212745/1.16.zip)
@diedyesterdaywashere
